# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Spectro.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(999, 722)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(500, 500))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.ref1 = QtGui.QCheckBox(self.groupBox)
        self.ref1.setObjectName(_fromUtf8("ref1"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ref1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.ref1Top = QtGui.QSlider(self.groupBox)
        self.ref1Top.setOrientation(QtCore.Qt.Horizontal)
        self.ref1Top.setObjectName(_fromUtf8("ref1Top"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ref1Top)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.ref1Bottom = QtGui.QSlider(self.groupBox)
        self.ref1Bottom.setOrientation(QtCore.Qt.Horizontal)
        self.ref1Bottom.setObjectName(_fromUtf8("ref1Bottom"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ref1Bottom)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.ref2 = QtGui.QCheckBox(self.groupBox_2)
        self.ref2.setObjectName(_fromUtf8("ref2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.ref2)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.ref2Top = QtGui.QSlider(self.groupBox_2)
        self.ref2Top.setOrientation(QtCore.Qt.Horizontal)
        self.ref2Top.setObjectName(_fromUtf8("ref2Top"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.ref2Top)
        self.ref2Bottom = QtGui.QSlider(self.groupBox_2)
        self.ref2Bottom.setOrientation(QtCore.Qt.Horizontal)
        self.ref2Bottom.setObjectName(_fromUtf8("ref2Bottom"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.ref2Bottom)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.sigTop = QtGui.QSlider(self.groupBox_5)
        self.sigTop.setOrientation(QtCore.Qt.Horizontal)
        self.sigTop.setObjectName(_fromUtf8("sigTop"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.sigTop)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.sigBottom = QtGui.QSlider(self.groupBox_5)
        self.sigBottom.setOrientation(QtCore.Qt.Horizontal)
        self.sigBottom.setObjectName(_fromUtf8("sigBottom"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.sigBottom)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.multisig = QtGui.QCheckBox(self.groupBox_3)
        self.multisig.setObjectName(_fromUtf8("multisig"))
        self.gridLayout.addWidget(self.multisig, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.NumSignals = QtGui.QSpinBox(self.groupBox_4)
        self.NumSignals.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NumSignals.setMinimum(1)
        self.NumSignals.setObjectName(_fromUtf8("NumSignals"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.NumSignals)
        self.SigSpacing = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.SigSpacing.setObjectName(_fromUtf8("SigSpacing"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.SigSpacing)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton.setEnabled(True)
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setAutoExclusive(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_2.addWidget(self.radioButton)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setAutoExclusive(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_4.addWidget(self.radioButton_2)
        self.rawsigStdDev = QtGui.QCheckBox(self.groupBox_7)
        self.rawsigStdDev.setChecked(False)
        self.rawsigStdDev.setObjectName(_fromUtf8("rawsigStdDev"))
        self.verticalLayout_4.addWidget(self.rawsigStdDev)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_3.setEnabled(True)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setAutoExclusive(True)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_3.addWidget(self.radioButton_3, 0, 0, 1, 1)
        self.sigStdDev = QtGui.QCheckBox(self.groupBox_8)
        self.sigStdDev.setChecked(False)
        self.sigStdDev.setObjectName(_fromUtf8("sigStdDev"))
        self.gridLayout_3.addWidget(self.sigStdDev, 1, 0, 1, 1)
        self.listSig = QtGui.QListView(self.groupBox_8)
        self.listSig.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listSig.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listSig.setObjectName(_fromUtf8("listSig"))
        self.gridLayout_3.addWidget(self.listSig, 0, 1, 2, 1)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.selRef1 = QtGui.QRadioButton(self.groupBox_9)
        self.selRef1.setEnabled(True)
        self.selRef1.setChecked(True)
        self.selRef1.setObjectName(_fromUtf8("selRef1"))
        self.gridLayout_4.addWidget(self.selRef1, 0, 0, 1, 1)
        self.refStdDev = QtGui.QCheckBox(self.groupBox_9)
        self.refStdDev.setChecked(True)
        self.refStdDev.setObjectName(_fromUtf8("refStdDev"))
        self.gridLayout_4.addWidget(self.refStdDev, 1, 0, 1, 1)
        self.selRef2 = QtGui.QRadioButton(self.groupBox_9)
        self.selRef2.setObjectName(_fromUtf8("selRef2"))
        self.gridLayout_4.addWidget(self.selRef2, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox_10)
        self.radioButton_5.setEnabled(False)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout_5.addWidget(self.radioButton_5)
        self.verticalLayout_7.addWidget(self.groupBox_10)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.multisig, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_4.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Reference 1", None))
        self.ref1.setText(_translate("MainWindow", "Use Reference 1", None))
        self.label.setText(_translate("MainWindow", "Top position", None))
        self.label_2.setText(_translate("MainWindow", "Bottom position", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Reference 2", None))
        self.ref2.setText(_translate("MainWindow", "Use Reference 2", None))
        self.label_3.setText(_translate("MainWindow", "Top position", None))
        self.label_4.setText(_translate("MainWindow", "Bottom position", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Online Reference", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Signal Selection", None))
        self.label_7.setText(_translate("MainWindow", "Top selection", None))
        self.label_8.setText(_translate("MainWindow", "Bottom selection", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Options", None))
        self.multisig.setText(_translate("MainWindow", "Use multi signals", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Multi Signals", None))
        self.label_5.setText(_translate("MainWindow", "Number of Signals", None))
        self.label_6.setText(_translate("MainWindow", "Signals Spacing", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Signals", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Plot #1", None))
        self.radioButton.setText(_translate("MainWindow", "2D - Raw signal", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Plot #2", None))
        self.radioButton_2.setText(_translate("MainWindow", "Mean rawsignal on selection", None))
        self.rawsigStdDev.setText(_translate("MainWindow", "Show StdDev", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Plot #3", None))
        self.radioButton_3.setText(_translate("MainWindow", "Flatfield", None))
        self.sigStdDev.setText(_translate("MainWindow", "Show StdDev", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Plot #4", None))
        self.selRef1.setText(_translate("MainWindow", "Mean Ref1", None))
        self.refStdDev.setText(_translate("MainWindow", "Show StdDev", None))
        self.selRef2.setText(_translate("MainWindow", "Mean Ref2", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Plot #5", None))
        self.radioButton_5.setText(_translate("MainWindow", "Nothing for the moment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Plots", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionOpen.setText(_translate("MainWindow", "Open SPE File", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))

